trigger:
- dev
pr:
- dev

pool:
  vmImage: "windows-latest"

steps:
- task: UsePythonVersion@0
  inputs: { versionSpec: '3.12' }

- script: |
    python -m pip install -U pip
    pip install -r requirements.txt
    pip install pytest pytest-cov
  displayName: "Install deps"

- script: |
    python -m pytest --junitxml=test-results.xml --cov=src --cov-report=xml
  displayName: "Run tests"

- task: PublishTestResults@2
  inputs:
    testResultsFormat: "JUnit"
    testResultsFiles: "test-results.xml"
    failTaskOnFailedTests: true
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@2
  inputs:
    codeCoverageTool: "Cobertura"
    summaryFileLocation: "coverage.xml"
