trigger:
  branches: { include: [ dev ] }   # CI on dev

pr:
  branches: { include: [ dev ] }

pool: { vmImage: ubuntu-latest }

variables:
  pythonVersion: '3.12'
  artifactName: 'drop'

stages:
- stage: CI
  displayName: Build & Test
  jobs:
  - job: test
    steps:
    - task: UsePythonVersion@0
      inputs: { versionSpec: '$(pythonVersion)' }

    - script: python -m pip install --upgrade pip
      displayName: Upgrade pip

    - script: pip install -r requirements.txt
      displayName: Install app dependencies

    - script: |
        pip install pytest pytest-azurepipelines
        pytest -q
      displayName: Run unit tests

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.SourcesDirectory)'
        artifactName: '$(artifactName)'

- stage: CD_Dev
  displayName: Deploy to Dev Web App
  dependsOn: CI
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  jobs:
  - deployment: deploy_dev
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)

          - task: AzureWebApp@1
            displayName: 'Deploy to calc-dev-web'
            inputs:
              azureSubscription: 'sc-azure-calculator'
              appType: 'webAppLinux'
              appName: 'calc-dev-web'
              package: '$(Pipeline.Workspace)/$(artifactName)'
              runtimeStack: 'PYTHON|3.12'
