# -----------------------------------------
# variables you already created as secrets:
# DEV_PUBPROFILE, PROD_PUBPROFILE
# -----------------------------------------

stages:
# ===== Build & Test =====
- stage: Build_Test
  displayName: Build + Test + Package
  jobs:
  - job: build
    displayName: Build & Test
    pool:
      name: Default
      demands:
      - Agent.OS -equals Windows_NT
    variables:
      packageDir: 'drop'
    steps:
    - checkout: self
      clean: true

    - task: CmdLine@2
      displayName: Show agent Python
      inputs:
        script: |
          ver
          where py
          py -3 --version

    - task: CmdLine@2
      displayName: Create venv & install deps
      inputs:
        script: |
          py -3 -m venv .venv
          .venv\Scripts\python -m pip install --upgrade pip wheel
          .venv\Scripts\pip install -r requirements.txt
          .venv\Scripts\pip install pytest pytest-cov

    - task: CmdLine@2
      displayName: Run pytest (with coverage)
      inputs:
        script: |
          if exist test-results rmdir /s /q test-results
          mkdir test-results
          .venv\Scripts\python -m pytest -q tests --junitxml=test-results\pytest.xml --cov=src --cov-report=xml

    - task: PublishTestResults@2
      displayName: Publish test results (JUnit)
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: 'test-results\pytest.xml'
        failTaskOnFailedTests: true

    - task: CmdLine@2
      displayName: Zip app
      inputs:
        script: |
          if exist "$(Build.ArtifactStagingDirectory)\app.zip" del /q "$(Build.ArtifactStagingDirectory)\app.zip"
          if exist _pkg rmdir /s /q _pkg
          mkdir _pkg
          xcopy /e /i /y src _pkg\src
          if exist run.sh copy /y run.sh _pkg\
          if exist run.bat copy /y run.bat _pkg\
          if exist requirements.txt copy /y requirements.txt _pkg\
          if exist pyproject.toml copy /y pyproject.toml _pkg\
          powershell -NoLogo -NoProfile -Command ^
            "Add-Type -AssemblyName System.IO.Compression.FileSystem; [IO.Compression.ZipFile]::CreateFromDirectory('_pkg', '$(Build.ArtifactStagingDirectory)\app.zip')"
          rmdir /s /q _pkg

    - task: PublishBuildArtifacts@1
      displayName: Publish artifact
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'

# ===== Deploy DEV (Linux) =====
- stage: Deploy_Dev
  displayName: Deploy to Dev (calc-dev-web)
  dependsOn: Build_Test
  condition: succeeded()
  jobs:
  - deployment: deploy_dev
    environment: dev-web
    strategy:
      runOnce:
        deploy:
          pool:
            name: Default
            demands:
            - Agent.OS -equals Windows_NT
          steps:
          - download: current
            artifact: drop

          # Ensure Linux app knows how to start: use run.sh at zip root
          - task: AzureAppServiceSettings@1
            displayName: App settings + startup (Linux)
            inputs:
              appName: 'calc-dev-web'
              appSettings: |
                -name SCM_DO_BUILD_DURING_DEPLOYMENT -value false -slotSetting false
                -name WEBSITES_ENABLE_APP_SERVICE_STORAGE -value true -slotSetting false
              startupCommand: 'bash run.sh'

          - task: AzureWebApp@1
            displayName: Zip Deploy to calc-dev-web (publish profile)
            inputs:
              appType: 'webAppLinux'
              appName: 'calc-dev-web'
              package: '$(Pipeline.Workspace)/drop/app.zip'
              publishProfile: '$(DEV_PUBPROFILE)'

# ===== Deploy PROD (Linux) =====
- stage: Deploy_Prod
  displayName: Deploy to Prod (calc-prod-web)
  dependsOn: Deploy_Dev
  condition: succeeded()
  jobs:
  - deployment: deploy_prod
    environment: prod-web
    strategy:
      runOnce:
        deploy:
          pool:
            name: Default
            demands:
            - Agent.OS -equals Windows_NT
          steps:
          - download: current
            artifact: drop

          - task: AzureAppServiceSettings@1
            displayName: App settings + startup (Linux)
            inputs:
              appName: 'calc-prod-web'
              appSettings: |
                -name SCM_DO_BUILD_DURING_DEPLOYMENT -value false -slotSetting false
                -name WEBSITES_ENABLE_APP_SERVICE_STORAGE -value true -slotSetting false
              startupCommand: 'bash run.sh'

          - task: AzureWebApp@1
            displayName: Zip Deploy to calc-prod-web (publish profile)
            inputs:
              appType: 'webAppLinux'
              appName: 'calc-prod-web'
              package: '$(Pipeline.Workspace)/drop/app.zip'
              publishProfile: '$(PROD_PUBPROFILE)'
